<?php

declare(strict_types=1);

namespace JardisCore\Foundation\Handler;

use JardisAdapter\EventDispatcher\EventDispatcher;
use JardisAdapter\EventDispatcher\ListenerProvider;
use JardisSupport\Contract\EventListener\EventListenerRegistryInterface;
use Psr\EventDispatcher\EventDispatcherInterface;

/**
 * Builds a PSR-14 event dispatcher with optional listener configurators.
 *
 * Requires jardisadapter/eventdispatcher. No ENV configuration needed —
 * the dispatcher is a pure in-memory service.
 *
 * Routes are callables that receive an EventListenerRegistryInterface
 * and register listeners on it. Typically these are EventRouter classes
 * generated by the Builder.
 *
 * Usage:
 *   $handler = new EventDispatcherHandler();
 *   $dispatcher = $handler($routerA, $routerB);
 */
final class EventDispatcherHandler
{
    /**
     * @param callable(EventListenerRegistryInterface): void ...$routes
     */
    public function __invoke(callable ...$routes): ?EventDispatcherInterface
    {
        if (!class_exists(EventDispatcher::class)) {
            return null;
        }

        $listener = new ListenerProvider();

        foreach ($routes as $route) {
            $route($listener);
        }

        return new EventDispatcher($listener);
    }
}
